# Generated by Django 5.1.3 on 2024-11-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expense',
            table='expense_app_expense',
        ),
    ]
